### ISSUE TITLE
How to use this in iOS?

### ISSUE THREAD

**Issue by Thavasidurai** [Tw1ddle/Rectangle-Bin-Packing#1]
Is it possible to use this in iOS project? If so, can you please guide me?

**Comment by Tw1ddle** [comment]
Hi, it would certainly be possible to use this if you compiled the library for the Haxe C++ target. OpenFL makes it easy to build a Haxe app for iOS in this way: http://www.openfl.org/learn/docs/getting-started/

Alternatively, if you want to use this in an Objective-C iOS project, you might prefer to use Jukka Jylänki's C++ rectangle bin packing code here:  https://github.com/juj/RectangleBinPack
